### PR TITLE
Add support for Rails 6

### LINKED ISSUE #84: activerecord 6
it does not work

### PR DESCRIPTION
**Pull request by greysteil**
Rails 6 is out - let's support it!

Fixes #84.

### CODE REVIEW

**Comment by fabdelgado** [comment]
It's necessary this patch, thanks @greysteil

**Comment by knapo** [comment]
👍

**Comment by greysteil** [comment]
@janko looks like it's a while since this gem had any commits or a release, but it would be *really* good to get this PR merged and released. 🙏

**Comment by tlrasor** [comment]
For testing purposes until the PR gets approved, 
`gem "sinatra-activerecord", git: "https://github.com/greysteil/sinatra-activerecord.git", branch: 'support-rails-6'`
👍 @greysteil  👍

**Comment by janko** [comment]
Thanks for the PR, merging 👍

**Comment by greysteil** [comment]
Thanks @janko!

**Comment by greysteil** [comment]
I've deleted this branch - anyone using it should switch to `gem 'sinatra-activerecord', '2.0.14'`.

Thanks for releasing @janko!

**Pull request merged**
